/* -*- js-indent-level: 8 -*- */
/*
 * Icon alias handler.
 */
/* global L $ */
L.Map.include({

	_iconAlias: {
		'acceptchanges': 'accepttrackedchanges',
		'accepttracedchange': 'accepttrackedchange',
		'adddatefield': 'datefield',
		'addname': 'label',
		'addons': 'insertplugin',
		'addtable': 'dbnewtable',
		'addtextbox': 'insertfixedtext',
		'adjust': 'zoomoptimal',
		'alignhorizontalceter': 'alignhorizontalcenter',
		'alignvcenter': 'alignverticalcenter',
		'anchormenu': 'toggleanchortype',
		'apply': 'ok',
		'arrangeframemenu': 'bringtofront',
		'arrangemenu': 'bringtofront',
		'arrowshapes.left-right-arrow': 'arrowshapes',
		'arrowstoolbox': 'linearrowend',
		'autofilter': 'datafilterautofilter',
		'autoformatmenu': 'autocorrectdlg',
		'availabletoolbars': 'showtoolbar',
		'backgroundpatterncontroller': 'backgroundcolor',
		'badcellstyle': 'badcellstyles',
		'basicshapes': 'basicshapes.diamond',
		'basicshapes.circle': 'circle',
		'basicshapes.circle-pie': 'pie',
		'basicshapes.ellipse': 'ellipse',
		'basicshapes.parallelogram': 'flowchartshapes.flowchart-data',
		'basicshapes.quadrat': 'square',
		'basicshapes.rectangle': 'rect',
		'basicshapes.round-rectangle': 'rect_rounded',
		'bezieredge': 'bezierappend',
		'browsebackward': 'prevrecord',
		'browseforward': 'nextrecord',
		'bulletliststyle': 'defaultbullet',
		'calloutshapes.round-rectangular-callout': 'calloutshapes',
		'cellcontentsmenu': 'calculate',
		'cellprotection': 'protect',
		'cellvertbottom': 'alignbottom',
		'cellvertcenter': 'alignverticalcenter',
		'cellverttop': 'aligntop',
		'centerpara': 'alignhorizontalcenter',
		'changesmenu': 'trackchanges',
		'characterbackgroundpattern': 'backcolor',
		'charactermenu': 'fontdialog',
		'charbackcolor': 'backcolor',
		'chartmenu': 'diagramtype',
		'charttitlemenu': 'toggletitle',
		'checkboxformfield': 'checkbox',
		'clickchangerotation': 'toggleobjectrotatemode',
		'closedocs': 'closedoc',
		'closewin': 'closepreview',
		'colorview': 'graphicfilterinvert',
		'columnoperations': 'entirecolumn',
		'columnwidth': 'setminimalcolumnwidth',
		'commentchange': 'commentchangetracking',
		'commonalignbottom': 'alignbottom',
		'commonalignhorizontalcenter': 'alignhorizontalcenter',
		'commonalignjustified': 'alignblock',
		'commonalignleft': 'alignleft',
		'commonalignright': 'alignright',
		'commonaligntop': 'aligntop',
		'commonalignverticalcenter': 'alignverticalcenter',
		'commontaskbarvisible': 'autopilotmenu',
		'com.sun.star.deployment.ui.packagemanagerdialog': 'insertplugin',
		'conditionalformatmenu': 'conditionalformatdialog',
		'config': 'choosecontrols',
		'connectorcircles': 'connector',
		'connectorcurvecircles': 'connectorcurve',
		'connectorlinecircles': 'connectorline',
		'connectorlinescircles': 'connector',
		'connectortoolbox': 'connector',
		'convertinto3dlathefast': 'convertinto3dlathe',
		'convertmenu': 'bezierconvert',
		'customanimation': 'diaeffect',
		'datafilterhideautofilter': 'removefiltersort',
		'datapilotmenu': 'datadatapilotrun',
		'datastreamsplay': 'runbasic',
		'datastreamsstop': 'basicstop',
		'datepickerformfield': 'datefield',
		'dbdtableedit': 'dbtableedit',
		'dbformopen': 'open',
		'dbqueryopen': 'open',
		'dbreportopen': 'open',
		'dbtableopen': 'open',
		'defaultcellstyles': 'defaultcharstyle',
		'defaultparastyle': 'controlcodes',
		'deleteallnotes': 'deleteallannotation',
		'deletecomment': 'deleteannotation',
		'deletenote': 'deleteannotation',
		'deleteshapehyperlink': 'removehyperlink',
		'diaauto': 'dia',
		'diagramaxisall': 'diagramaxisxyz',
		'diagramaxismenu': 'diagramaxis',
		'diagramgridmenu': 'togglegridhorizontal',
		'donation': 'currencyfield',
		'draw': 'reload',
		'drawselect': 'selectobject',
		'drawtext': 'text',
		'dropdownformfield': 'combobox',
		'dsbdocumentdatasource': 'insertexternaldatasource',
		'dsbeditdoc': 'editdoc',
		'dsbinsertcolumns': 'insertfieldctrl',
		'editlinksmenu': 'insertreferencefield',
		'editpastespecialmenu': 'pastespecial',
		'editselectmenu': 'selecttables',
		'editshapehyperlink': 'inserthyperlink',
		'editstyled': 'editstyle',
		'ellipsetoolbox': 'ellipse',
		'exitsearch': 'closepreview',
		'exportasgraphic': 'insertgraphic',
		'exportasmenu': 'exportto',
		'exporttoepub': 'exportdirecttoepub',
		'exporttopdf': 'exportdirecttopdf',
		'extrusiontoggle': 'convertinto3d',
		'fieldmenu': 'addfield',
		'fieldnames': 'addfield',
		'fillcolor': 'backgroundcolor',
		'fillstyle': 'backgroundcolor',
		'filtercrit': 'datafilterstandardfilter',
		'findbar': 'recsearch',
		'firstpage': 'firstrecord',
		'firstslide': 'firstrecord',
		'fliphorizontal': 'mirror',
		'flipmenu': 'mirror',
		'flipvertical': 'mirrorvert',
		'flowchartshapes.flowchart-alternate-process': 'basicshapes.round-quadrat',
		'flowchartshapes.flowchart-connector': 'circle',
		'flowchartshapes.flowchart-extract': 'basicshapes.isosceles-triangle',
		'flowchartshapes.flowchart-magnetic-disk': 'basicshapes.can',
		'flowchartshapes.flowchart-manual-operation': 'basicshapes.trapezoid',
		'flowchartshapes.flowchart-merge': 'fontworkshapetype.fontwork-triangle-down',
		'flowchartshapes.flowchart-process': 'square',
		'focustofindbar': 'recsearch',
		'fontcolor': 'color',
		'fontheight': 'scaletext',
		'fontworkalignmentfloater': 'alignhorizontalcenter',
		'fontworkcharacterspacingfloater': 'spacing',
		'fontworkshapetype': 'fontwork',
		'fontworkshapetype.fontwork-circle-pour': 'basicshapes.ring',
		'fontworkshapetype.fontwork-fade-down': 'basicshapes.trapezoid',
		'fontworkshapetype.fontwork-triangle-up': 'basicshapes.isosceles-triangle',
		'footnotecellstyles': 'insertfootnote',
		'formatarea': 'backgroundcolor',
		'formatbulletsmenu': 'defaultbullet',
		'formatframemenu': 'framedialog',
		'formatimagemenu': 'graphic',
		'formatselection': 'configuredialog',
		'formatspacingmenu': 'spacepara15',
		'formattextmenu': 'charfontname',
		'formfilter': 'datafilterspecialfilter',
		'formfilterexecute': 'datafilterstandardfilter',
		'functionbox': 'dbviewfunctions',
		'functiondialog': 'dbviewfunctions',
		'goodcellstyle': 'goodcellstyles',
		'gotoendofdoc': 'lastrecord',
		'gotostartofdoc': 'firstrecord',
		'grafattrcrop': 'crop',
		'grafinvert': 'graphicfilterinvert',
		'grafmode': 'graphicdialog',
		'graphicfilterposter': 'graphicdialog',
		'graphicfiltertoolbox': 'autopilotmenu',
		'graphicmenu': 'avmediaplayer',
		'grid': 'insertspreadsheet',
		'gridmenu': 'gridvisible',
		'groupmenu': 'formatgroup',
		'groupoutlinemenu': 'group',
		'headerandfooter': 'editheaderandfooter',
		'heading1cellstyles': 'heading1parastyle',
		'heading2cellstyles': 'heading2parastyle',
		'helperdialog': 'helpindex',
		'hscroll': 'hscrollbar',
		'hyperlinkdialog': 'inserthyperlink',
		'hyphenation': 'hyphenate',
		'indexesmenu': 'insertindexesentry',
		'inputlinevisible': 'dbviewfunctions',
		'insertannotation': 'shownote',
		'insertauthorfield': 'dbviewaliases',
		'insertavmedia': 'avmediaplayer',
		'insertcell': 'insertcellsright',
		'insertcolumns': 'insertcolumnsafter',
		'insertcolumnsmenu': 'insertcolumnsafter',
		'insertcontents': 'pastespecial',
		'insertctrl': 'inserttable',
		'insertcurrencyfield': 'currencyfield',
		'insertcurrentdate': 'datefield',
		'insertcurrenttime': 'timefield',
		'insertdatefield': 'datefield',
		'insertdatefieldfix': 'datefield',
		'insertdatefieldvar': 'datefield',
		'insertedit': 'edit',
		'insertfield': 'addfield',
		'insertfilecontrol': 'filecontrol',
		'insertfilefield': 'filefield',
		'insertfootnotesmenu': 'insertfootnote',
		'insertformattedfield': 'formattedfield',
		'insertformcheck': 'checkbox',
		'insertformcombo': 'combobox',
		'insertformhscroll': 'hscrollbar',
		'insertformlist': 'listbox',
		'insertformmenu': 'choosecontrols',
		'insertformradio': 'radiobutton',
		'insertformspin': 'spinbutton',
		'insertformula': 'dbviewfunctions',
		'insertformvscroll': 'scrollbar',
		'insertframeinteract': 'insertframe',
		'insertframeinteractnocolumns': 'insertframe',
		'insertgridcontrol': 'insertspreadsheet',
		'insertheaderfootermenu': 'editheaderandfooter',
		'insertimagecontrol': 'imagecontrol',
		'insertlistbox': 'listbox',
		'insertmenuaxes': 'diagramaxis',
		'insertmenugrids': 'togglegridhorizontal',
		'insertmenulegend': 'legend',
		'insertnumericfield': 'numberformatstandard',
		'insertobjctrl': 'drawchart',
		'insertobjectchart': 'drawchart',
		'insertobjectchartfromfile': 'open',
		'insertobjectdialog': 'insertobject',
		'insertobjectstarmath': 'insertmath',
		'insertpagefield': 'insertpagenumberfield',
		'insertpagefooter': 'insertfooter',
		'insertpageheader': 'insertheader',
		'insertpagenumber': 'insertpagenumberfield',
		'insertpagesfield': 'insertpagecountfield',
		'insertpagetitlefield': 'inserttitlefield',
		'insertpatternfield': 'patternfield',
		'insertpushbutton': 'pushbutton',
		'insertrows': 'insertrowsafter',
		'insertrowsmenu': 'insertrowsafter',
		'insertscript': 'choosemacro',
		'insertsignatureline': 'signaturelinedialog',
		'insertslidefield': 'insertslidenumberfield',
		'insertslidenumber': 'insertslidenumberfield',
		'insertslidesfield': 'insertslidecountfield',
		'inserttextframe': 'insertframe',
		'inserttimefieldfix': 'timefield',
		'inserttimefield': 'timefield',
		'inserttimefieldvar': 'timefield',
		'inserttoolbox': 'dataimport',
		'insobjctrl': 'newdoc',
		'justifypara': 'alignblock',
		'languagemenu': 'managelanguage',
		'lastpage': 'lastrecord',
		'lastslide': 'lastrecord',
		'leftpara': 'alignleft',
		'librelogo-gobackward': 'arrowshapes.down-arrow',
		'librelogo-goforward': 'arrowshapes.up-arrow',
		'librelogo-run': 'runbasic',
		'librelogo-stop': 'basicstop',
		'librelogo-translate': 'editglossary',
		'linenumberdialog': 'linenumberingdialog',
		'linespacing': 'spacepara15',
		'linetoolbox': 'freeline_unfilled',
		'loadstyles': 'open',
		'macrodialog': 'scriptorganizer',
		'macroorganizer%3ftabid%3ashort=1': 'open',
		'macroorganizer': 'scriptorganizer',
		'macrosmenu': 'choosemacro',
		'mailmergefirstentry': 'firstrecord',
		'mailmergelastentry': 'lastrecord',
		'mailmergenextentry': 'nextrecord',
		'mailmergepreventry': 'prevrecord',
		'margins': 'pagemargin',
		'measureattributes': 'measureline',
		'mergecellsmenu': 'togglemergecells',
		'mergedocument': 'mergedocuments',
		'mirrorhorz': 'mirror',
		'mirrormenu': 'rotateleft',
		'modifypage': 'slidesetup',
		'movepagedown': 'downsearch',
		'movepageup': 'upsearch',
		'moveslidedown': 'downsearch',
		'moveslidefirst': 'movepagefirst',
		'moveslidelast': 'movepagelast',
		'moveslideup': 'upsearch',
		'namegroup': 'definename',
		'navigateback': 'prevrecord',
		'navigateforward': 'nextrecord',
		'neutralcellstyle': 'neutralcellstyles',
		'nextpage': 'nextrecord',
		'nextslide': 'nextrecord',
		'no': 'cancel',
		'notecellstyles': 'shownote',
		'notevisible': 'shownote',
		'numberformatcurrencysimple': 'numberformatcurrency',
		'numberformatmenu': 'numberformatstandard',
		'numberingmenu': 'outlinebullet',
		'numberliststyle': 'defaultnumbering',
		'numericfield': 'numberformatstandard',
		'objectalign': 'objectalignleft',
		'objectmenu': 'formatobjectmenu',
		'objectmirrorhorizontal': 'mirror',
		'objectmirrorvertical': 'mirrorvert',
		'objects3dtoolbox': 'cube',
		'objecttitledescription': 'insertcaptiondialog',
		'openfromcalc': 'open',
		'openfromwriter': 'open',
		'open_h': 'open',
		'openhyperlinkoncursor': 'inserthyperlink',
		'openurl': 'browseview',
		'openxmlfiltersettings': 'managexmlsource',
		'ordercrit': 'datasort',
		'outlinedown': 'movedown',
		'outlineleft': 'incrementlevel',
		'outlineright': 'decrementlevel',
		'outlineup': 'moveup',
		'outputqualitycolor': 'insertgraphic',
		'pagedown': 'nextrecord',
		'pageformatdialog': 'pagedialog',
		'pageup': 'prevrecord',
		'paragraphmenu': 'paragraphdialog',
		'pastespecialmenu': 'pastespecial',
		'pluginsactive': 'insertplugin',
		'previewprintoptions': 'printpreview',
		'previewzoom': 'zoom',
		'previouspage': 'prevrecord',
		'previousslide': 'prevrecord',
		'printpagepreview': 'printpreview',
		'printrangesmenu': 'defineprintarea',
		'questionanswers': 'browseview',
		'quickedit': 'editdoc',
		'rectangletoolbox': 'rect',
		'recundo': 'undo',
		'refresh': 'reload',
		'removefilter': 'removefiltersort',
		'renametable': 'name',
		'repaginate': 'insertpagenumberfield',
		'rightpara': 'alignright',
		'rotateflipmenu': 'rotateleft',
		'rowheight': 'setminimalrowheight',
		'rowoperations': 'entirerow',
		'rulermenu': 'ruler',
		'rulerrows': 'extrusiontiltleft',
		'rulerrowsvertical': 'extrusiontiltright',
		'savegraphic': 'save',
		'savesimple': 'save',
		'sbabrwinsert': 'insertfieldctrl',
		'scrollbarmenu': 'scrollbar',
		'scrolltonext': 'downsearch',
		'scrolltoprevious': 'upsearch',
		'sectionalignbottom': 'aligndown',
		'sectionalignleft': 'objectalignleft',
		'sectionalignright': 'objectalignright',
		'sectionaligntop': 'alignup',
		'selectcolumn': 'entirecolumn',
		'selectdata': 'selectdb',
		'selectmode': 'selectobject',
		'selectrow': 'entirerow',
		'sendfeedback': 'insertenvelope',
		'setdefault': 'resetattributes',
		'setoptimalcolumnwidthdirect': 'setoptimalcolumnwidth',
		'settabbgcolor': 'backgroundcolor',
		'shapeslinemenu': 'line',
		'shapesmenu': 'insertdraw',
		'sheetcommentmenu': 'shownote',
		'sheetlefttoright': 'paralefttoright',
		'sheetrighttoleft': 'pararighttoleft',
		'showallnotes': 'showannotations',
		'showbrowser': 'controlproperties',
		'showchanges': 'showtrackedchanges',
		'showgraphics': 'graphic',
		'showinlinetooltips': 'shownote',
		'showpropbrowser': 'controlproperties',
		'showruler': 'ruler',
		'sidebarmenu': 'sidebar',
		'sortdialog': 'datasort',
		'sortdown': 'sortdescending',
		'sortup': 'sortascending',
		'sourceview': 'symbolshapes.brace-pair',
		'spelldialog': 'spelling',
		'spellingandgrammardialog': 'spelling',
		'starchartdialog': 'drawchart',
		'symbolcatalogue': 'insertsymbol',
		'symbolshapes.smiley': 'symbolshapes',
		'tableautofitmenu': 'setoptimalrowheight',
		'tablecellbackgroundcolor': 'backgroundcolor',
		'tabledeletemenu': 'deletetable',
		'tableevents': 'animationeffects',
		'tableinsertmenu': 'insertrowsafter',
		'tablemenu': 'tabledialog',
		'tableselectmenu': 'selecttable',
		'tablesort': 'sortascending',
		'templatemenu': 'templatemanager',
		'textalign': 'alignblock',
		'textattributes': 'fontdialog',
		'textfittosizetool': 'text_marquee',
		'textformfield': 'edit',
		'texttoolbox': 'text',
		'thesaurusdialog': 'thesaurus',
		'toggleaxisdescr': 'helplinesvisible',
		'toolbarsmenu': 'showtoolbar',
		'toolsformsmenu': 'dbviewforms',
		'toolsmacroedit': 'basicideappear',
		'tracechangemode': 'trackchanges',
		'underlinesimple': 'underline',
		'underlinesingle': 'underline',
		'updateallindexes': 'insertmultiindex',
		'updatealllinks': 'inserthyperlink',
		'updateall': 'reload',
		'updatecharts': 'drawchart',
		'updatefields': 'addfield',
		'updatemenu': 'reload',
		'usewizards': 'autopilotmenu',
		'view100': 'zoom100percent',
		'view3d': 'cube',
		'viewsidebarstyles': 'designerdialog',
		'viewtrackchanges': 'showtrackedchanges',
		'vscrollbar': 'scrollbar',
		'vscroll': 'scrollbar',
		'webhtml': 'browseview',
		'wrapmenu': 'wrapon',
		'xlinestyle': 'linestyle',
		'yes': 'ok',
		'zoomminus': 'zoomout',
		'zoomplus': 'zoomin',
		'zoomtoolbox': 'zoom'
	},

	// 帶參數的 uno 指令(.uno:AssignLayout?WhatLayer=xx)
	_resorceIcon: {
		'.uno:AssignLayout?WhatLayout:long=20': 'layout_empty', // 空白投影片
		'.uno:AssignLayout?WhatLayout:long=19': 'layout_head01', // 只有題名
		'.uno:AssignLayout?WhatLayout:long=0': 'layout_head03', // 題名投影片
		'.uno:AssignLayout?WhatLayout:long=1': 'layout_head02', // 題名、內容區塊
		'.uno:AssignLayout?WhatLayout:long=32': 'layout_textonly', // 文字置中

		'.uno:AssignLayout?WhatLayout:long=3': 'layout_head02a', // 題名和2個內容區塊
		'.uno:AssignLayout?WhatLayout:long=12': 'layout_head03c', // 題名、內容區塊和2個內容區塊
		'.uno:AssignLayout?WhatLayout:long=15': 'layout_head03b', // 題名、2個內容區塊和內容區塊
		'.uno:AssignLayout?WhatLayout:long=14': 'layout_head02b', // 題名、內容區塊在內容區塊之上
		'.uno:AssignLayout?WhatLayout:long=16': 'layout_head03a', // 題名、2個內容區塊在內容區塊之上
		'.uno:AssignLayout?WhatLayout:long=18': 'layout_head04', // 題名、4個內容區塊
		'.uno:AssignLayout?WhatLayout:long=34': 'layout_head06', // 題名、6個內容區塊

		'.uno:AssignLayout?WhatLayout:long=28': 'layout_vertical01', // 垂直題名、垂直文字
		'.uno:AssignLayout?WhatLayout:long=27': 'layout_vertical02', // 垂直題名、文字、圖表
		'.uno:AssignLayout?WhatLayout:long=29': 'layout_head02', // 題名、垂直文字
		'.uno:AssignLayout?WhatLayout:long=30': 'layout_head02a', // 題名、垂直文字、美術圖形
	},

	// Add by Firefly <firefly@ossii.com.tw>
	// 依據 itemKey 設定右鍵選單 icon 圖示
	contextMenuIcon: function($itemElement, itemKey, item) {
		// 如果有 checktype
		if (item.checktype !== undefined && item.checked) {
			$itemElement.addClass('lo-menu-item-checked');
		} else {
			$itemElement.removeClass('lo-menu-item-checked');
		}
		var hasinit = $itemElement.hasClass('_init_');
		if (hasinit) {return '';}
		$itemElement.addClass('_init_')
		// 設定 icon
		var icon = L.DomUtil.create('i', 'menuicon img-icon');
		var iconURL = 'url("' + this.getUnoCommandIcon(itemKey) + '")';
		$(icon).css('background-image', iconURL);
		$itemElement.append(icon);
		return '';
	},

	// Add by Firefly <firefly@ossii.com.tw>
	// 把 uno 指令轉換成 icon 圖示 URL
	getUnoCommandIcon: function(unoCommand) {
		if (this._resorceIcon[unoCommand]) {
			return L.Icon.Default.imagePath + '/res/' + this._resorceIcon[unoCommand] + '.svg';
		}

		var command = unoCommand.toLowerCase(); // 轉成小寫
		if (command.startsWith('.uno:')) {
			command = command.substr(5);
		} else if (command.startsWith('dialog:')) {
			command = command.substr(7);
		}

		var icon = this._iconAlias[command] ? this._iconAlias[command] : command;

		return L.Icon.Default.imagePath + '/cmd/' + icon + '.svg';
	}
});
