{
 "title": "OxOffice Online / HA - Allocation",
 "tags": [
  "collabora",
  "app"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "env_id",
    "query": {
     "query": "label_values(oxoolwsd_count{}, env_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_node_name{env_id=~\"$env_id\"})by(env_id)",
     "legendFormat": "{{env_id}}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(oxoolwsd_count{env_id=~\"$env_id\"})by(env_id)",
     "legendFormat": "{{env_id}}"
    }
   ]
  },
  {
   "title": "Open Docs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kit_assigned_count{env_id=~\"$env_id\"})by(env_id)",
     "legendFormat": "{{env_id}}"
    }
   ]
  },
  {
   "title": "Highes Viewer on Doc",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(doc_views_active{env_id=~\"$env_id\"})by(env_id)",
     "legendFormat": "{{env_id}}"
    }
   ]
  },
  {
   "title": "Viewers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(document_active_views_active_count_total{env_id=~\"$env_id\"})by(env_id)",
     "legendFormat": "{{env_id}}"
    }
   ]
  },
  {
   "title": "Documents per WOPI-Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count(doc_info{env_id=~\"$env_id\"})by(host,env_id)",
     "legendFormat": "{{env_id}}: {{host}}"
    }
   ]
  },
  {
   "title": "Usage Overview (ENV_ID: $env_id)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "repeat": "env_id",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(oxoolwsd_count{env_id=~\"$env_id\"})by(env_id)",
     "legendFormat": "Pods"
    },
    {
     "expr": "sum(kit_assigned_count{env_id=~\"$env_id\"})by(env_id)",
     "legendFormat": "Docs"
    },
    {
     "expr": "sum(document_active_views_active_count_total{env_id=~\"$env_id\"})by(env_id)",
     "legendFormat": " Viewers on Pod"
    }
   ]
  },
  {
   "title": "Docs on  Pod (ENV_ID: $env_id)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "repeat": "env_id",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(kit_assigned_count{env_id=~\"$env_id\"})by(env_id)",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(kit_assigned_count{env_id=~\"$env_id\"})by(env_id)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Viewer on  Pod (ENV_ID: $env_id)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "repeat": "env_id",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(document_active_views_active_count_total{env_id=~\"$env_id\"})by(env_id)",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(document_active_views_active_count_total{env_id=~\"$env_id\"})by(env_id)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Viewer on  Doc (ENV_ID: $env_id)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "repeat": "env_id",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(doc_views_active{env_id=~\"$env_id\"})by(env_id)",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(doc_views_active{env_id=~\"$env_id\"})by(env_id)",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Error: Duplicated Documents (All ENV_ID)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(count(doc_info{env_id=~\"$env_id\"})by(key)>1)",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(count(doc_info{env_id=~\"$env_id\"})by(key)>1)",
     "legendFormat": "Max"
    },
    {
     "expr": "count(count(doc_info{env_id=~\"$env_id\"})by(key)>1)",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Duplicated Documents",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(doc_info{env_id=~\"$env_id\"})by(key,env_id)>1)by(env_id)",
     "legendFormat": "{{env_id}}"
    }
   ]
  },
  {
   "title": "Storage SpaceLow",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(error_storage_space_low{env_id=~\"$env_id\"}[5m]))by(env_id)",
     "legendFormat": "{{env_id}}"
    }
   ]
  },
  {
   "title": "Storage Connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(error_storage_connection{env_id=~\"$env_id\"}[5m]))by(env_id)",
     "legendFormat": "{{env_id}}"
    }
   ]
  },
  {
   "title": "Bad Argument",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(error_bad_argument{env_id=~\"$env_id\"}[5m]))by(env_id)",
     "legendFormat": "{{env_id}}"
    }
   ]
  },
  {
   "title": "Unauthorized Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(error_unauthorized_request{env_id=~\"$env_id\"}[5m]))by(env_id)",
     "legendFormat": "{{env_id}}"
    }
   ]
  },
  {
   "title": "Service Unavailable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(error_service_unavailable{env_id=~\"$env_id\"}[5m]))by(env_id)",
     "legendFormat": "{{env_id}}"
    }
   ]
  },
  {
   "title": "Parse Error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(error_parse_error{env_id=~\"$env_id\"}[5m]))by(env_id)",
     "legendFormat": "{{env_id}}"
    }
   ]
  },
  {
   "title": "Bad Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(error_bad_request{env_id=~\"$env_id\"}[5m]))by(env_id)",
     "legendFormat": "{{env_id}}"
    }
   ]
  },
  { "title": "HA - Allocation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Document per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "count(kit_assigned_count{env_id=~\"$env_id\"}==0)",
     "legendFormat": "Viewers: 0"
    },
    {
     "expr": "count(kit_assigned_count{env_id=~\"$env_id\"}==1)",
     "legendFormat": "Viewers: 1"
    },
    {
     "expr": "count(kit_assigned_count{env_id=~\"$env_id\"}==2)",
     "legendFormat": "Viewers: 2"
    },
    {
     "expr": "count(kit_assigned_count{env_id=~\"$env_id\"}==3)",
     "legendFormat": "Viewers: 3"
    },
    {
     "expr": "count(kit_assigned_count{env_id=~\"$env_id\"}==4)",
     "legendFormat": "Viewers: 3"
    },
    {
     "expr": "count(kit_assigned_count{env_id=~\"$env_id\"}==5)",
     "legendFormat": "Viewers: 5"
    },
    {
     "expr": "count(5<kit_assigned_count{env_id=~\"$env_id\"}<10)",
     "legendFormat": "Viewers: 5-10"
    },
    {
     "expr": "count(10<kit_assigned_count{env_id=~\"$env_id\"}<15)",
     "legendFormat": "Viewers: 10-15"
    },
    {
     "expr": "count(15<kit_assigned_count{env_id=~\"$env_id\"}<20)",
     "legendFormat": "Viewers: 15-20"
    },
    {
     "expr": "count(20<kit_assigned_count{env_id=~\"$env_id\"}<25)",
     "legendFormat": "Viewers: 20-25"
    },
    {
     "expr": "count(25<kit_assigned_count{env_id=~\"$env_id\"}<30)",
     "legendFormat": "Viewers: 25-30"
    },
    {
     "expr": "count(30<kit_assigned_count{env_id=~\"$env_id\"}<35)",
     "legendFormat": "Viewers: 30-35"
    },
    {
     "expr": "count(35<kit_assigned_count{env_id=~\"$env_id\"})",
     "legendFormat": "Viewers: 30-Inf"
    }
   ]
  },
  {
   "title": "Pods hold Documents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 41 },
   "targets": [
    {
     "expr": "count_values(\"pod\", kit_assigned_count{env_id=~\"$env_id\"})",
     "legendFormat": "{{pod}} docs are open on Pod:"
    }
   ]
  },
  {
   "title": "Viewer per Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "count(document_active_views_active_count_total{env_id=~\"$env_id\"}==0)",
     "legendFormat": "Viewers: 0"
    },
    {
     "expr": "count(document_active_views_active_count_total{env_id=~\"$env_id\"}==1)",
     "legendFormat": "Viewers: 1"
    },
    {
     "expr": "count(document_active_views_active_count_total{env_id=~\"$env_id\"}==2)",
     "legendFormat": "Viewers: 2"
    },
    {
     "expr": "count(document_active_views_active_count_total{env_id=~\"$env_id\"}==3)",
     "legendFormat": "Viewers: 3"
    },
    {
     "expr": "count(document_active_views_active_count_total{env_id=~\"$env_id\"}==4)",
     "legendFormat": "Viewers: 3"
    },
    {
     "expr": "count(document_active_views_active_count_total{env_id=~\"$env_id\"}==5)",
     "legendFormat": "Viewers: 5"
    },
    {
     "expr": "count(5<document_active_views_active_count_total{env_id=~\"$env_id\"}<10)",
     "legendFormat": "Viewers: 5-10"
    },
    {
     "expr": "count(10<document_active_views_active_count_total{env_id=~\"$env_id\"}<15)",
     "legendFormat": "Viewers: 10-15"
    },
    {
     "expr": "count(15<document_active_views_active_count_total{env_id=~\"$env_id\"}<20)",
     "legendFormat": "Viewers: 15-20"
    },
    {
     "expr": "count(20<document_active_views_active_count_total{env_id=~\"$env_id\"}<25)",
     "legendFormat": "Viewers: 20-25"
    },
    {
     "expr": "count(25<document_active_views_active_count_total{env_id=~\"$env_id\"}<30)",
     "legendFormat": "Viewers: 25-30"
    },
    {
     "expr": "count(30<document_active_views_active_count_total{env_id=~\"$env_id\"}<35)",
     "legendFormat": "Viewers: 30-35"
    },
    {
     "expr": "count(35<document_active_views_active_count_total{env_id=~\"$env_id\"})",
     "legendFormat": "Viewers: 30-Inf"
    }
   ]
  },
  {
   "title": "Pods hold Viewers (active views)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 49 },
   "targets": [
    {
     "expr": "count_values(\"pod\", document_active_views_active_count_total{env_id=~\"$env_id\"})",
     "legendFormat": "{{pod}} viewers are open on Pod:"
    }
   ]
  },
  {
   "title": "Docs on Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(kit_assigned_count{env_id=~\"$env_id\"}) by (env_id,pod)",
     "legendFormat": "{{env_id}}: {{pod}}"
    }
   ]
  },
  {
   "title": "Viewers on Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(document_active_views_active_count_total{env_id=~\"$env_id\"}) by (env_id,pod)",
     "legendFormat": "{{env_id}}: {{pod}}"
    }
   ]
  }
 ]
}